### ISSUE TITLE
camera recordings and screencasts won't start simultaneously

### ISSUE THREAD

**Issue by ofthelake** [StepicOrg/Stepik-Studio#29] opened 2018-06-17 11:31 UTC
the recording of a screencast is usually delayed by half a second, and so camera recordings and screencasts have to be synchronised in post-production, which sometimes can be tricky because the exact time of the delay varies.

**Comment by vyahhi** [comment] 2018-07-31 11:41
TODO: check time sync algorithms from realtime distributed systems

**Comment by vyahhi** [comment] 2018-07-31 11:49
maybe: make camera+screencast synchronization by audio AFTER recording, automatically

**Comment by vyahhi** [comment] 2018-10-16 13:30
Should be fixed in #43 (together with issue #31):
(1) Latency between the server and tablet has been dramatically reduced, so the issue is not here anymore.
(2) Anyway, audio tracks are syncing now (we detect and align silences at the beginnings of tracks).

**Closed by vyahhi** 2018-10-16 13:30 UTC
Labels: bug
